[package]
name = "packmule"
version = "0.8.0"
authors = ["Jack Polgar <jack@polgar.id.au>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde_yaml = "0.8"
tempdir = "0.3.7"
walkdir = "2.2.9"
glob = "0.3.0"
