[package]
name = "packmule"
version = "0.8.0"
authors = ["Jack Polgar <jack@polgar.id.au>"]
edition = "2018"

[dependencies]
clap = "2.33"
serde_yaml = "0.8"
tempdir = "0.3"
walkdir = "2.2"
glob = "0.3"
tar = "0.4"
flate2 = "1.0"
